substitutions:
  name: "pompe_doseuses_esphome"
  friendly_name: "Pompes doseuses récifales"
  comment: "pompe_doseuses ESP32 - controleur d'aquarium récifal"
  project_name: "Twinsen68.pompe_doseuses"
  app_version: "1.0"
  logger: "DEBUG"
  sorting_group_name: "pompe_doseuses "
  name_add_mac_suffix: "false"

esp32:
  board: esp32dev  # Spécifie le modèle de la carte ESP32 (ESP32 DevKit V1 ici).
  framework:
    type: arduino  # Utilisation du framework Arduino

# Inclusion d'une configuration externe pour modularité et réutilisation.
packages:
  twinsen68.pompe_doseuses_esphome:
    url: https://github.com/Twinsen68/pompe_doseuses_esphome
    file: pompedoseuses_config.yaml
    ref: main

api:
  encryption:
    key: tsHqLo48mLGhWo/qQQrZUFdsEwuZcC1/BlUOXWExy14=

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

time:
  - platform: sntp
    id: my_time
